---
- name: Install ansible.windows collection
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if ansible.windows collection is installed
      command: ansible-galaxy collection list ansible.windows
      register: result
      ignore_errors: true

    - name: Install ansible.windows collection if not installed
      command: ansible-galaxy collection install ansible.windows
      when: result.rc != 0
