- name: Install FortiClient VPN and place shortcut on all desktops
  hosts: all
  gather_facts: no
  vars:
    installer_url: "https://github.com/Mustak22/FortiClient-VPN-Installer/releases/download/v1.0/FortiClientVPNInstaller.exe"
    installer_path: "C:\\Temp\\FortiClientVPNInstaller.exe"
    exe_path: "C:\\Program Files\\FortiClient\\FortiClient.exe"
    shortcut_admin: "C:\\Users\\Administrator\\Desktop\\FortiClient.lnk"
    shortcut_public: "C:\\Users\\Public\\Desktop\\FortiClient.lnk"
    public_desktop_dir: "C:\\Users\\Public\\Desktop"

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download FortiClient VPN installer (with increased timeout)
      win_get_url:
        url: "{{ installer_url }}"
        dest: "{{ installer_path }}"
        timeout: 600  # Increase timeout to 10 minutes
      ignore_errors: yes  # In case of download failure

    - name: Check if the installer was downloaded
      stat:
        path: "{{ installer_path }}"
      register: installer_stat

    - name: Manual download fallback (if the previous download failed)
      win_command: "curl -L -o {{ installer_path }} {{ installer_url }}"
      when: installer_stat.stat.exists == false

    - name: Install FortiClient VPN silently using win_command
      win_command: "{{ installer_path }} /quiet"
      args:
        chdir: "C:\\Temp"
      when: installer_stat.stat.exists == true

    - name: Create shortcut on Administrator desktop
      win_shortcut:
        src: "{{ exe_path }}"
        dest: "{{ shortcut_admin }}"

    - name: Ensure Public Desktop directory exists
      win_file:
        path: "{{ public_desktop_dir }}"
        state: directory

    - name: Copy shortcut to Public desktop (visible to all users)
      win_copy:
        src: "{{ shortcut_admin }}"
        dest: "{{ shortcut_public }}"
        remote_src: true

    - name: Cleanup installer
      win_file:
        path: "{{ installer_path }}"
        state: absent
