---
- name: Download and install FortiClient on Windows
  hosts: all  # This will target all hosts in your inventory
  gather_facts: false

  vars:
    installer_url: "https://fortinet.com/path/to/actual-installer.exe"  # Correct URL from Fortinet's website
    installer_path: "C:\\Temp\\FortiClientInstaller.exe"
    exe_path: "C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe"
    shortcut_admin: "C:\\Users\\Administrator\\Desktop\\FortiClient.lnk"
    shortcut_public: "C:\\Users\\Public\\Desktop\\FortiClient.lnk"
    public_desktop_dir: "C:\\Users\\Public\\Desktop"

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download FortiClient installer
      win_get_url:
        url: "{{ installer_url }}"
        dest: "{{ installer_path }}"

    - name: Install FortiClient silently using win_command
      win_command: "{{ installer_path }} /quiet"
      args:
        chdir: "C:\\Temp"

    - name: Create shortcut on Administrator desktop
      win_shortcut:
        src: "{{ exe_path }}"
        dest: "{{ shortcut_admin }}"

    - name: Ensure Public Desktop directory exists
      win_file:
        path: "{{ public_desktop_dir }}"
        state: directory

    - name: Copy shortcut to Public desktop (visible to all users)
      win_copy:
        src: "{{ shortcut_admin }}"
        dest: "{{ shortcut_public }}"
        remote_src: true

    - name: Cleanup installer
      win_file:
        path: "{{ installer_path }}"
        state: absent
