- name: Install FortiClient VPN
  hosts: windows_machines  # or your relevant host group
  gather_facts: yes
  tasks:
    - name: Copy FortiClient VPN installer to target machine
      win_copy:
        src: files/FortiClientVPNInstaller.exe
        dest: C:\Temp\FortiClientVPNInstaller.exe

    - name: Run the installer silently
      win_command: C:\Temp\FortiClientVPNInstaller.exe /quiet
      args:
        creates: C:\Program Files\Postman\FortiClientVPN.exe  # Adjust the path to check if FortiClient is installed.

    - name: Create shortcut on all user desktops
      win_shortcut:
        path: C:\Users\Public\Desktop\FortiClientVPN.lnk
        target: C:\Program Files\Postman\FortiClientVPN.exe  # Adjust the target path accordingly.
        arguments: ''
        description: 'FortiClient VPN'
        icon: 'C:\Program Files\Postman\FortiClientVPN.ico'  # Change if you have an icon.
