---
- name: Check Java Services on Remote Host
  hosts: transit_server
  become: true
  tasks:
    - name: Check if Eureka Server is running
      shell: pgrep -f eureka-server
      register: eureka_status
      ignore_errors: true

    - name: Report Eureka Server Status
      debug:
        msg: >-
          {{ '✅ Eureka Server is running.' if eureka_status.rc == 0 else '❌ Eureka Server is NOT running.' }}

    - name: Check if Zuul Gateway is running
      shell: pgrep -f zuul
      register: zuul_status
      ignore_errors: true

    - name: Report Zuul Gateway Status
      debug:
        msg: >-
          {{ '✅ Zuul Gateway is running.' if zuul_status.rc == 0 else '❌ Zuul Gateway is NOT running.' }}

    - name: Check if Config Server is running
      shell: pgrep -f config-server
      register: config_status
      ignore_errors: true

    - name: Report Config Server Status
      debug:
        msg: >-
          {{ '✅ Config Server is running.' if config_status.rc == 0 else '❌ Config Server is NOT running.' }}

    # Add more services as needed following the same pattern
