- name: Install FortiClient VPN and place shortcut on all desktops
  hosts: all
  gather_facts: no
  vars:
    forticlient_download_url: "https://filestore.fortinet.com/forticlient/downloads/FortiClientVPN_OnlineInstaller.exe"
    forticlient_installer_path: "C:\\Temp\\FortiClientVPNInstaller.exe"
    forticlient_shortcut_path: "C:\\Users\\Public\\Desktop\\FortiClient VPN.lnk"

  tasks:
    - name: Ensure Temp directory exists on target
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download FortiClient VPN installer from internet
      win_get_url:
        url: "{{ forticlient_download_url }}"
        dest: "{{ forticlient_installer_path }}"
        validate_certs: no  # Set to yes if using HTTPS and cert is valid

    - name: Install FortiClient VPN silently
      win_package:
        path: "{{ forticlient_installer_path }}"
        arguments: "/quiet"
        state: present

    - name: Ensure FortiClient VPN shortcut exists on Public Desktop
      win_shortcut:
        src: "C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe"
        dest: "{{ forticlient_shortcut_path }}"

    - name: ✅ Confirm FortiClient installation completed
      debug:
        msg: "✅ FortiClient VPN has been successfully installed and shortcut placed."
