- name: Install ONLYOFFICE Desktop Editors on Windows
  hosts: all
  gather_facts: yes

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download ONLYOFFICE installer
      win_get_url:
        url: "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x64.exe"
        dest: "C:\\Temp\\OnlyOfficeDesktopEditors_x64.exe"

    - name: Install ONLYOFFICE
      win_command: "C:\\Temp\\OnlyOfficeDesktopEditors_x64.exe /silent"

    - name: Cleanup installer
      win_file:
        path: "C:\\Temp\\OnlyOfficeDesktopEditors_x64.exe"
        state: absent

    - name: ✅ ONLYOFFICE successfully installed
      debug:
        msg: "✅ ONLYOFFICE Desktop Editors installed successfully on {{ inventory_hostname }}"
