- name: Install FortiClient VPN and place shortcut on all desktops
  hosts: all
  gather_facts: no
  vars:
    forticlient_download_url: "https://links.fortinet.com/forticlient/win64/fabricagent"
    forticlient_installer_path: "C:\\Temp\\FortiClientVPNInstaller.exe"
    forticlient_exe_path: "C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe"
    forticlient_shortcut_path: "C:\\Users\\Public\\Desktop\\FortiClient VPN.lnk"

  tasks:
    - name: Ensure Temp directory exists on target
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download FortiClient VPN installer from Fortinet
      win_get_url:
        url: "{{ forticlient_download_url }}"
        dest: "{{ forticlient_installer_path }}"
        validate_certs: yes

    - name: Install FortiClient VPN silently
      win_package:
        path: "{{ forticlient_installer_path }}"
        arguments: "/quiet"
        state: present

    - name: Wait until FortiClient is installed
      win_wait_for:
        path: "{{ forticlient_exe_path }}"
        state: present
        timeout: 180

    - name: Create FortiClient VPN shortcut on Public Desktop
      win_shortcut:
        src: "{{ forticlient_exe_path }}"
        dest: "{{ forticlient_shortcut_path }}"

    - name: Cleanup FortiClient installer
      win_file:
        path: "{{ forticlient_installer_path }}"
        state: absent

    - name: ✅ Confirm FortiClient VPN installation completed
      debug:
        msg: "✅ FortiClient VPN installed and shortcut placed successfully."
