- name: Install FortiClient VPN for currently logged-in user
  hosts: all
  gather_facts: yes
  vars:
    forticlient_download_url: "https://links.fortinet.com/forticlient/win64/fabricagent"
    forticlient_installer_path: "C:\\Temp\\FortiClientVPNInstaller.exe"

  tasks:

    - name: Ensure Temp directory exists on target
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download FortiClient VPN installer from Fortinet
      win_get_url:
        url: "{{ forticlient_download_url }}"
        dest: "{{ forticlient_installer_path }}"
        validate_certs: yes
        timeout: 300

    - name: Install FortiClient VPN silently
      win_command: "{{ forticlient_installer_path }} /quiet /norestart"

    - name: ✅ Confirm FortiClient installation completed
      debug:
        msg: "✅ FortiClient VPN installed successfully."
