- name: Install FortiClient VPN for currently logged-in user
  hosts: all
  gather_facts: yes
  vars:
    forticlient_download_url: "https://links.fortinet.com/forticlient/win64/fabricagent"
    forticlient_installer_path: "C:\\Temp\\FortiClientVPNInstaller.exe"

  tasks:

    - name: Ensure Temp directory exists on target
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download FortiClient VPN installer from Fortinet
      win_get_url:
        url: "{{ forticlient_download_url }}"
        dest: "{{ forticlient_installer_path }}"
        validate_certs: yes
        timeout: 300

    - name: Install FortiClient VPN silently
      win_command: "{{ forticlient_installer_path }} /quiet /norestart"

    - name: Get currently logged-in user
      win_shell: |
        (Get-CimInstance -ClassName Win32_ComputerSystem).UserName
      register: logged_in_user_raw

    - name: Fail if no user is logged in
      fail:
        msg: "❌ No user currently logged in. Cannot place shortcut."
      when: logged_in_user_raw.stdout == ""

    - name: Extract username from DOMAIN\\Username
      set_fact:
        logged_in_user: "{{ logged_in_user_raw.stdout.split('\\\\')[-1] }}"

    - name: Create FortiClient shortcut on current user's Desktop
      win_shortcut:
        src: "C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe"
        dest: "C:\\Users\\{{ logged_in_user }}\\Desktop\\FortiClient VPN.lnk"

    - name: ✅ Confirm FortiClient installation completed
      debug:
        msg: "✅ FortiClient VPN has been successfully installed and shortcut placed for user {{ logged_in_user }}"
