- name: Install ONLYOFFICE Desktop Editors on Windows
  hosts: all
  gather_facts: false

  vars:
    installer_url: "https://download.onlyoffice.com/install/desktop/editors/windows/OnlyOfficeDesktopEditors_x64.exe"
    installer_path: "C:\\Temp\\OnlyOfficeDesktopEditors_x64.exe"

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download ONLYOFFICE installer
      win_get_url:
        url: "{{ installer_url }}"
        dest: "{{ installer_path }}"

    - name: Run the ONLYOFFICE installer silently
      win_package:
        path: "{{ installer_path }}"
        arguments: "/quiet"
        product_id: 'ONLYOFFICE Desktop Editors'
        state: present

    - name: ✅ ONLYOFFICE installed successfully
      debug:
        msg: "✅ ONLYOFFICE Desktop Editors has been installed on the system."
