---
- name: Bootstrap Python 3.10 on Ubuntu 24.04
  hosts: 192.168.5.18
  become: true
  tasks:
    - name: Install dependencies for Python 3.10
      raw: |
        apt-get update && apt-get install -y \
        software-properties-common \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        wget \
        curl \
        llvm \
        libncurses5-dev \
        libncursesw5-dev \
        xz-utils \
        tk-dev \
        libffi-dev \
        liblzma-dev \
        python3-openssl

    - name: Add deadsnakes PPA for Python 3.10
      raw: apt-add-repository ppa:deadsnakes/ppa -y && apt-get update

    - name: Install Python 3.10
      raw: apt-get install -y python3.10

    - name: Set Python 3.10 as the default Python
      raw: update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

    - name: Verify Python version
      raw: python --version
