---
- name: Install Adobe Acrobat Reader DC on Windows
  hosts: all
  gather_facts: no
  vars:
    acrobat_installer_url: "https://get.adobe.com/reader/download/?installer=Reader_DC_XX&os=win&standalone=1"
    acrobat_installer_path: "C:\\Temp\\AcroReaderInstaller.exe"
    acrobat_install_path: "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader"

  tasks:
    - name: Create Temp directory
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download Acrobat Reader installer
      win_get_url:
        url: "{{ acrobat_installer_url }}"
        dest: "{{ acrobat_installer_path }}"
        checksum: "sha256:PLACE-CHECKSUM-HERE" # Optional: If you have a checksum for validation

    - name: Install Acrobat Reader silently
      win_command:
        cmd: "{{ acrobat_installer_path }} /sAll /msi EULA_ACCEPT=YES"
        creates: "{{ acrobat_install_path }}"

    - name: Remove the installer after installation
      win_file:
        path: "{{ acrobat_installer_path }}"
        state: absent

    - name: Verify Acrobat Reader installation
      win_stat:
        path: "{{ acrobat_install_path }}"
      register: acrobat_installed

    - name: Show installation status
      debug:
        msg: "Adobe Acrobat Reader DC has been installed."
      when: acrobat_installed.stat.exists

    - name: Fail if Acrobat installation was not successful
      fail:
        msg: "Adobe Acrobat Reader DC installation failed."
      when: not acrobat_installed.stat.exists
