- name: Install ChatGPT Desktop App on Windows
  hosts: all
  gather_facts: no
  vars:
    chatgpt_download_url: "https://aka.ms/windowsdesktopchatgpt"
    chatgpt_installer_path: "C:\\Temp\\ChatGPTSetup.exe"

  tasks:

    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download ChatGPT installer
      win_get_url:
        url: "{{ chatgpt_download_url }}"
        dest: "{{ chatgpt_installer_path }}"

    - name: Install ChatGPT silently
      win_package:
        path: "{{ chatgpt_installer_path }}"
        arguments: "/quiet"
        product_id: ""  # leave blank, silent install handles this
        state: present

    - name: Remove installer after installation
      win_file:
        path: "{{ chatgpt_installer_path }}"
        state: absent
