- name: Show pop-up message on Windows for 10 seconds
  hosts: all
  gather_facts: no
  tasks:
    - name: Show pop-up message every second
      win_command: >
        powershell -WindowStyle Hidden -Command "
        Add-Type -AssemblyName PresentationFramework;
        for ($i = 1; $i -le 10; $i++) {
            [System.Windows.MessageBox]::Show('I am Monitoring... #'+$i);
            Start-Sleep -Seconds 1
        }"
