- name: Show auto-closing popup using PowerShell
  hosts: all
  gather_facts: no
  tasks:
    - name: Show auto-closing popup
      win_shell: |
        powershell -WindowStyle Hidden -Command "
        Add-Type -AssemblyName PresentationFramework;
        $window = New-Object Windows.Window;
        $window.Content = '🔍 I am Monitoring...';
        $window.Width = 300;
        $window.Height = 100;
        $window.Topmost = $true;
        $window.Show();
        Start-Sleep -Seconds 10;
        $window.Close();"
