- name: Install Postman and move shortcut to logged-in user's desktop
  hosts: all
  gather_facts: no
  vars:
    choco_path: C:\ProgramData\chocolatey\bin\choco.exe
    postman_package: postman
    postman_exe_path: C:\Users\Administrator\AppData\Local\Postman\Postman.exe
    shortcut_src: C:\Users\Administrator\Desktop\Postman.lnk

  tasks:

    - name: Install Chocolatey (if not present)
      win_command: |
        powershell -NoProfile -ExecutionPolicy Bypass -Command "if (!(Test-Path '{{ choco_path }}')) { iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) }"
      args:
        creates: "{{ choco_path }}"

    - name: Install Postman using Chocolatey
      win_command: "{{ choco_path }} install {{ postman_package }} -y"

    - name: Wait for Postman installation to complete
      pause:
        seconds: 10

    - name: Find Postman.exe
      win_find:
        paths: C:\Users\Administrator\AppData\Local\Postman\
        patterns: Postman.exe
      register: postman_check

    - name: Get currently logged-in user (DOMAIN\username)
      win_shell: |
        (Get-CimInstance -ClassName Win32_ComputerSystem).UserName
      register: loggedin_user_raw

    - name: Extract only username part (after \)
      set_fact:
        current_user: "{{ loggedin_user_raw.stdout | regex_replace('.*\\\\', '') | trim }}"

    - name: Move shortcut to currently logged-in user's Desktop
      win_command: |
        powershell -NoProfile -ExecutionPolicy Bypass -Command "Move-Item -Path '{{ shortcut_src }}' -Destination 'C:\Users\{{ current_user }}\Desktop\' -Force"
      args:
        removes: "{{ shortcut_src }}"
      when: postman_check.matched > 0
