- name: Uninstall Postman from all possible locations
  hosts: all
  gather_facts: no
  vars:
    choco_path: "C:\\ProgramData\\chocolatey\\bin\\choco.exe"
    postman_programfiles_path: "C:\\Program Files\\Postman"
    postman_localappdata_path: "C:\\Users\\Administrator\\AppData\\Local\\Postman"
    postman_shortcut_public: "C:\\Users\\Public\\Desktop\\Postman.lnk"
    postman_shortcut_admin: "C:\\Users\\Administrator\\Desktop\\Postman.lnk"
    postman_zip_path: "C:\\Temp\\Postman-win64.zip"

  tasks:

    - name: Check if Chocolatey is installed
      win_stat:
        path: "{{ choco_path }}"
      register: choco_exists

    - name: Uninstall Postman via Chocolatey (if installed)
      win_command: "{{ choco_path }} uninstall postman -y"
      when: choco_exists.stat.exists
      register: choco_uninstall
      failed_when: false
      changed_when: "'postman is not installed' not in choco_uninstall.stdout"

    - name: Debug Chocolatey uninstall output
      debug:
        var: choco_uninstall.stdout_lines
      when: choco_exists.stat.exists

    - name: Remove Postman from Program Files
      win_file:
        path: "{{ postman_programfiles_path }}"
        state: absent

    - name: Remove Postman from LocalAppData (Administrator)
      win_file:
        path: "{{ postman_localappdata_path }}"
        state: absent

    - name: Remove Postman shortcut from Public Desktop
      win_file:
        path: "{{ postman_shortcut_public }}"
        state: absent

    - name: Remove Postman shortcut from Administrator Desktop
      win_file:
        path: "{{ postman_shortcut_admin }}"
        state: absent

    - name: Remove leftover ZIP installer if present
      win_file:
        path: "{{ postman_zip_path }}"
        state: absent

    - name: ✅ Confirm Postman uninstallation complete
      debug:
        msg: "✅ Postman has been successfully uninstalled and all known leftovers cleaned."
