- name: Install Postman and place shortcut on all desktops
  hosts: all
  gather_facts: no
  vars:
    installer_url: "https://dl.pstmn.io/download/latest/win64"  # Official Postman Windows 64-bit installer
    installer_path: "C:\\Temp\\Postman-win64-setup.exe"
    exe_path: "C:\\Users\\{{ ansible_user }}\\AppData\\Local\\Postman\\Postman.exe"
    shortcut_admin: "C:\\Users\\Administrator\\Desktop\\Postman.lnk"
    shortcut_public: "C:\\Users\\Public\\Desktop\\Postman.lnk"
    public_desktop_dir: "C:\\Users\\Public\\Desktop"

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download Postman installer
      win_get_url:
        url: "{{ installer_url }}"
        dest: "{{ installer_path }}"

    - name: Install Postman silently
      win_command: "{{ installer_path }} /silent"
      args:
        chdir: "C:\\Temp"

    - name: Wait for Postman installation to complete
      win_wait_for:
        path: "{{ exe_path }}"
        state: present
        timeout: 120

    - name: Create shortcut on Administrator desktop
      win_shortcut:
        src: "{{ exe_path }}"
        dest: "{{ shortcut_admin }}"

    - name: Ensure Public Desktop directory exists
      win_file:
        path: "{{ public_desktop_dir }}"
        state: directory

    - name: Copy shortcut to Public desktop (visible to all users)
      win_copy:
        src: "{{ shortcut_admin }}"
        dest: "{{ shortcut_public }}"
        remote_src: true

    - name: Cleanup Postman installer
      win_file:
        path: "{{ installer_path }}"
        state: absent

    - name: ✅ Confirm successful installation
      debug:
        msg: "✅ Postman has been installed and shortcuts placed on all desktops."
