- name: Install Postman and move shortcut to logged-in user's desktop
  hosts: all
  gather_facts: no
  vars:
    choco_path: C:\ProgramData\chocolatey\bin\choco.exe
    postman_package: postman

  tasks:

    - name: Install Chocolatey (if not present)
      win_command: |
        powershell -NoProfile -ExecutionPolicy Bypass -Command "if (!(Test-Path '{{ choco_path }}')) { iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) }"
      args:
        creates: "{{ choco_path }}"

    - name: Install Postman using Chocolatey
      win_command: "{{ choco_path }} install {{ postman_package }} -y"

    - name: Find Postman.exe
      win_find:
        paths:
          - 'C:\Users'
          - 'C:\Program Files'
          - 'C:\Program Files (x86)'
        patterns: 'Postman.exe'
      register: postman_files

    - name: Get currently logged-in user
      win_command: powershell -Command "(Get-WmiObject -Class Win32_ComputerSystem).UserName"
      register: loggedin_user_raw

    - name: Extract username
      set_fact:
        current_user: "{{ loggedin_user_raw.stdout.split('\\')[-1] }}"

    - name: Create shortcut on logged-in user’s desktop
      win_shortcut:
        src: "{{ postman_files.files[0].path }}"
        dest: "C:\\Users\\{{ current_user }}\\Desktop\\Postman.lnk"
      when: postman_files.matched > 0
