- name: Install Postman system-wide and make available to all users
  hosts: all
  gather_facts: no
  vars:
    postman_download_url: https://dl.pstmn.io/download/latest/win64
    postman_zip_path: C:\Temp\Postman-win64.zip
    postman_install_path: C:\Program Files\Postman
    postman_exe_path: C:\Program Files\Postman\Postman.exe
    shortcut_path: C:\Users\Public\Desktop\Postman.lnk

  tasks:

    - name: Create temp directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Download Postman ZIP
      win_get_url:
        url: "{{ postman_download_url }}"
        dest: "{{ postman_zip_path }}"

    - name: Create install directory
      win_file:
        path: "{{ postman_install_path }}"
        state: directory

    - name: Unzip Postman to Program Files
      win_unzip:
        src: "{{ postman_zip_path }}"
        dest: "{{ postman_install_path }}"
        remote_src: yes

    - name: Create Postman shortcut on public desktop
      win_shortcut:
        src: "{{ postman_exe_path }}"
        dest: "{{ shortcut_path }}"

    - name: Cleanup downloaded zip
      win_file:
        path: "{{ postman_zip_path }}"
        state: absent
