- name: Install Apache HTTP Server
  hosts: all
  become: yes
  tasks:
    - name: Update dnf cache
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install Apache (httpd) on Rocky Linux (RHEL-based)
      package:
        name: httpd
        state: present
