---
- name: Install Postman and create shortcut
  hosts: all
  connection: ssh
  gather_facts: false

  tasks:
    - name: Full installation and shortcut creation
      raw: |
        powershell -command "
        # Install Postman
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $url = 'https://dl.pstmn.io/download/latest/win64'
        $output = \"$env:TEMP\\Postman.exe\"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -Wait -FilePath $output -ArgumentList '/S'
        Remove-Item $output -Force

        # Create shortcut
        $desktop = [System.Environment]::GetFolderPath('Desktop')
        $shortcut = \"$desktop\\Postman.lnk\"
        $target = \"$env:LOCALAPPDATA\\Postman\\Postman.exe\"
        $wshell = New-Object -ComObject WScript.Shell
        $sc = $wshell.CreateShortcut($shortcut)
        $sc.TargetPath = $target
        $sc.Save()
        "
