---
- name: Install Python 3 on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Ensure python3 is installed
      apt:
        name: python3
        state: present
        update_cache: yes

    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Ensure python3-venv is installed (optional, if you want virtual environments)
      apt:
        name: python3-venv
        state: present

    - name: Ensure python3-setuptools is installed
      apt:
        name: python3-setuptools
        state: present

    - name: Verify Python3 installation
      command: python3 --version
      register: python3_version
      ignore_errors: yes

    - name: Show Python3 version
      debug:
        msg: "Python3 version: {{ python3_version.stdout }}"
