- name: Install Apache Web Server
  hosts: all  # This targets all hosts in the inventory
  become: yes  # This allows the playbook to run tasks with escalated privileges (e.g., sudo)
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: yes
