- name: Force Uninstall FortiClient VPN from Windows
  hosts: all
  gather_facts: no
  vars:
    uninstall_path: 'C:\\Program Files\\Fortinet\\FortiClient\\uninstall.exe'
    forticlient_exe: 'C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe'
    forticlient_folder: 'C:\\Program Files\\Fortinet'

  tasks:

    - name: Kill FortiClient-related processes
      win_shell: |
        Get-Process FortiClient* -ErrorAction SilentlyContinue | Stop-Process -Force
      ignore_errors: yes

    - name: Stop FortiClient services
      win_service:
        name: "{{ item }}"
        state: stopped
        start_mode: disabled
      loop:
        - FCTserv
        - FCTAppEventSvc
        - FortiESNAC
      ignore_errors: yes

    - name: Try to run the official FortiClient uninstaller (quoted path)
      win_command: '"{{ uninstall_path }}" /quiet /norestart'
      register: uninstall_result
      ignore_errors: yes

    - name: Wait for FortiClient to be removed
      win_wait_for:
        path: "{{ forticlient_exe }}"
        state: absent
        timeout: 180
      ignore_errors: yes

    - name: Take ownership and delete FortiClient folder
      win_shell: |
        takeown /f "{{ forticlient_folder }}" /r /d y
        icacls "{{ forticlient_folder }}" /grant Administrators:F /t
        Remove-Item -Path "{{ forticlient_folder }}" -Recurse -Force
      args:
        executable: powershell
      ignore_errors: yes

    - name: Delete FortiClient shortcuts from all desktops
      win_find:
        paths: ['C:\\Users']
        patterns: 'FortiClient*.lnk'
        recurse: yes
      register: fc_shortcuts

    - name: Remove detected FortiClient shortcuts
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ fc_shortcuts.files }}"
      when: fc_shortcuts.matched > 0

    - name: ✅ Confirm FortiClient uninstall attempt completed
      debug:
        msg: "🧹 FortiClient uninstall attempted. Check system manually if parts remain."
