- name: Uninstall Notepad++ if found
  hosts: all
  gather_facts: no
  tasks:

    - name: Check if Notepad++ is installed in default path
      win_stat:
        path: 'C:\Program Files\Notepad++\uninstall.exe'
      register: np_uninstaller

    - name: Uninstall Notepad++ silently
      win_command: '"C:\Program Files\Notepad++\uninstall.exe" /S'
      when: np_uninstaller.stat.exists
