- name: Uninstall Notepad++ and clean up shortcuts
  hosts: all
  gather_facts: no
  vars:
    npp_uninstaller_path: "C:\\Program Files\\Notepad++\\uninstall.exe"
    npp_program_dir: "C:\\Program Files\\Notepad++"
    shortcut_admin: "C:\\Users\\Administrator\\Desktop\\Notepad++.lnk"
    shortcut_public: "C:\\Users\\Public\\Desktop\\Notepad++.lnk"
    installer_path: "C:\\Temp\\npp_installer.exe"

  tasks:
    - name: Check if Notepad++ uninstaller exists
      win_stat:
        path: "{{ npp_uninstaller_path }}"
      register: npp_uninstaller

    - name: Run Notepad++ uninstaller silently
      win_command: '"{{ npp_uninstaller_path }}" /S'
      when: npp_uninstaller.stat.exists

    - name: Remove Notepad++ program directory (if exists)
      win_file:
        path: "{{ npp_program_dir }}"
        state: absent

    - name: Remove shortcut from Administrator desktop
      win_file:
        path: "{{ shortcut_admin }}"
        state: absent

    - name: Remove shortcut from Public desktop
      win_file:
        path: "{{ shortcut_public }}"
        state: absent

    - name: Remove installer if it still exists
      win_file:
        path: "{{ installer_path }}"
        state: absent
