- name: Uninstall FortiClient VPN from Windows
  hosts: all
  gather_facts: no
  vars:
    uninstall_path: "C:\\Program Files\\Fortinet\\FortiClient\\uninstall.exe"
    forticlient_exe: "C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe"

  tasks:

    - name: Check if FortiClient uninstaller exists
      win_stat:
        path: "{{ uninstall_path }}"
      register: uninstaller

    - name: Run FortiClient uninstaller silently
      win_command: "{{ uninstall_path }} /quiet /norestart"
      when: uninstaller.stat.exists
      register: uninstall_result
      ignore_errors: yes

    - name: Wait for uninstallation to complete
      win_wait_for:
        path: "{{ forticlient_exe }}"
        state: absent
        timeout: 180
      when: uninstaller.stat.exists

    - name: Confirm FortiClient has been uninstalled
      debug:
        msg: "✅ FortiClient VPN has been uninstalled."
