- name: Uninstall ONLYOFFICE Desktop Editors on Windows
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get ONLYOFFICE uninstall string from registry
      win_reg_stat:
        path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
        recursive: yes
      register: reg_info

    - name: Set uninstall string variable
      set_fact:
        onlyoffice_uninstall_string: "{{ item.value['UninstallString'] }}"
      when: "'ONLYOFFICE Desktop Editors' in item.value['DisplayName']"
      with_items: "{{ reg_info.sub_keys | map('win_reg_stat', recursive=false) | list }}"
      loop_control:
        label: "{{ item.key }}"
      register: uninstall_command

    - name: Run uninstall command for ONLYOFFICE
      win_command: "{{ uninstall_command.results | selectattr('ansible_facts.onlyoffice_uninstall_string', 'defined') | map(attribute='ansible_facts.onlyoffice_uninstall_string') | first }} /quiet"
      when: uninstall_command.results | selectattr('ansible_facts.onlyoffice_uninstall_string', 'defined') | list | length > 0

    - name: Remove ONLYOFFICE shortcut from current user desktop
      win_shell: |
        $user = (Get-WmiObject -Class Win32_ComputerSystem).UserName.Split('\\')[-1]
        $desktopPath = "C:\\Users\\$user\\Desktop\\ONLYOFFICE.lnk"
        if (Test-Path $desktopPath) {
            Remove-Item $desktopPath -Force
        }

    - name: ✅ ONLYOFFICE successfully uninstalled
      debug:
        msg: "✅ ONLYOFFICE Desktop Editors uninstalled successfully on {{ inventory_hostname }}"
