- name: Uninstall FortiClient VPN from Windows
  hosts: all
  gather_facts: no
  vars:
    forticlient_uninstaller_path: "C:\\Program Files\\Fortinet\\FortiClient\\uninst.exe"
    forticlient_exe_path: "C:\\Program Files\\Fortinet\\FortiClient\\FortiClient.exe"

  tasks:

    - name: Check if FortiClient uninstaller exists
      win_stat:
        path: "{{ forticlient_uninstaller_path }}"
      register: uninstaller_exists

    - name: Run FortiClient uninstaller silently
      win_command: "{{ forticlient_uninstaller_path }} /quiet /norestart"
      when: uninstaller_exists.stat.exists
      register: uninstall_result

    - name: Wait for FortiClient.exe to be removed
      win_wait_for:
        path: "{{ forticlient_exe_path }}"
        state: absent
        timeout: 180
      when: uninstaller_exists.stat.exists

    - name: Confirm FortiClient uninstallation complete
      debug:
        msg: "✅ FortiClient has been uninstalled."
