- name: Uninstall Notepad++ and clean up shortcuts
  hosts: all
  gather_facts: no
  tasks:

    - name: Check if Notepad++ uninstaller exists
      win_stat:
        path: 'C:\Program Files\Notepad++\uninstall.exe'
      register: uninstall_file

    - name: Run Notepad++ uninstaller silently
      win_command: '"C:\Program Files\Notepad++\uninstall.exe" /S'
      when: uninstall_file.stat.exists

    - name: Kill Notepad++ process (if running)
      win_shell: |
        try {
          Get-Process "notepad++" -ErrorAction Stop | Stop-Process -Force
        } catch {
          Write-Output "Notepad++ process not found or already terminated."
        }

    - name: Force remove Notepad++ program directory (even if files are locked)
      win_shell: |
        try {
          Remove-Item 'C:\Program Files\Notepad++' -Recurse -Force -ErrorAction Stop
          Write-Output "Notepad++ directory removed successfully."
        } catch {
          Write-Output "Failed to remove Notepad++ directory: $_"
        }

    - name: Remove Admin desktop shortcut
      win_file:
        path: 'C:\Users\Administrator\Desktop\Notepad++.lnk'
        state: absent

    - name: Remove Public desktop shortcut
      win_file:
        path: 'C:\Users\Public\Desktop\Notepad++.lnk'
        state: absent
