- name: Uninstall Notepad++ and clean up shortcuts
  hosts: all
  gather_facts: no
  tasks:

    - name: Check if Notepad++ uninstaller exists
      win_stat:
        path: 'C:\Program Files\Notepad++\uninstall.exe'
      register: uninstall_file

    - name: Run Notepad++ uninstaller silently
      win_command: '"C:\Program Files\Notepad++\uninstall.exe" /S'
      when: uninstall_file.stat.exists

    - name: Kill Notepad++ process (if running)
      win_shell: |
        Stop-Process -Name notepad++ -Force -ErrorAction SilentlyContinue

    - name: Remove Notepad++ program directory (if exists)
      win_file:
        path: 'C:\Program Files\Notepad++'
        state: absent

    - name: Remove Admin desktop shortcut
      win_file:
        path: 'C:\Users\Administrator\Desktop\Notepad++.lnk'
        state: absent

    - name: Remove Public desktop shortcut
      win_file:
        path: 'C:\Users\Public\Desktop\Notepad++.lnk'
        state: absent
