- name: Uninstall ONLYOFFICE Desktop Editors on Windows
  hosts: all
  gather_facts: yes

  tasks:
    - name: Search ONLYOFFICE uninstall string in registry
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
        recursive: yes
      register: reg_info

    - name: Extract ONLYOFFICE uninstall string
      win_reg_stat:
        path: "{{ item }}"
      register: uninstall_data
      with_items: "{{ reg_info.sub_keys }}"
      when: "'ONLYOFFICE Desktop Editors' in item"
      loop_control:
        label: "{{ item }}"
      ignore_errors: yes

    - name: Set uninstall command variable
      set_fact:
        onlyoffice_uninstall_cmd: "{{ item.value.UninstallString }}"
      when: item.value.UninstallString is defined
      with_items: "{{ uninstall_data.results }}"
      register: uninstall_cmd_set

    - name: Run ONLYOFFICE uninstall command
      win_command: "{{ uninstall_cmd_set.results | selectattr('ansible_facts.onlyoffice_uninstall_cmd', 'defined') | map(attribute='ansible_facts.onlyoffice_uninstall_cmd') | first }} /quiet"
      when: uninstall_cmd_set.results | selectattr('ansible_facts.onlyoffice_uninstall_cmd', 'defined') | list | length > 0

    - name: Get currently logged-in username
      win_shell: "(Get-WmiObject -Class Win32_ComputerSystem).UserName.Split('\\')[1]"
      register: current_user

    - name: Remove ONLYOFFICE shortcut from current user desktop
      win_file:
        path: "C:\\Users\\{{ current_user.stdout }}\\Desktop\\ONLYOFFICE.lnk"
        state: absent

    - name: ✅ ONLYOFFICE successfully uninstalled
      debug:
        msg: "✅ ONLYOFFICE Desktop Editors uninstalled and cleaned up on {{ inventory_hostname }}"
