- name: Reboot Windows machine immediately
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot the machine
      win_reboot:
        reboot_timeout: 600
        msg: "Reboot initiated by Ansible."
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: 'whoami'
