- name: Upgrade Windows 10 Pro to Windows 11 Pro using Installation Assistant (via Task Scheduler)
  hosts: all
  gather_facts: no
  vars:
    assistant_url: "https://go.microsoft.com/fwlink/?linkid=2171764"
    assistant_path: "C:\\Temp\\Windows11InstallationAssistant.exe"

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download Windows 11 Installation Assistant
      win_get_url:
        url: "{{ assistant_url }}"
        dest: "{{ assistant_path }}"
        validate_certs: yes

    - name: Create a scheduled task to launch the installer in interactive mode
      win_shell: |
        schtasks /create /tn "Win11Upgrade" /tr "{{ assistant_path }}" /sc once /st 00:00 /rl highest /f

    - name: Run the scheduled task immediately
      win_shell: |
        schtasks /run /tn "Win11Upgrade"

    - name: ✅ Task launched — user needs to complete upgrade
      debug:
        msg: "✅ Upgrade task scheduled and started. It will show up for the currently logged-in user."
