- name: Upgrade Windows 10 Pro to Windows 11 Pro (Safe Upgrade)
  hosts: all
  gather_facts: no
  vars:
    iso_download_url: "https://software-download.microsoft.com/pr/Win11_23H2_English_x64v2.iso"
    iso_path: "C:\\Temp\\Win11.iso"
    mount_drive: "E:"
    setup_path: "E:\\setup.exe"

  tasks:

    - name: Create Temp folder if not exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download Windows 11 ISO
      win_get_url:
        url: "{{ iso_download_url }}"
        dest: "{{ iso_path }}"
        timeout: 600
        validate_certs: no

    - name: Mount the Windows 11 ISO
      win_shell: |
        PowerShell Mount-DiskImage -ImagePath "{{ iso_path }}"
      args:
        executable: powershell.exe

    - name: Wait for ISO to mount and setup.exe to appear
      win_wait_for:
        path: "{{ setup_path }}"
        timeout: 60

    - name: Start Windows 11 upgrade (safe in-place)
      win_command: "{{ setup_path }} /auto upgrade /quiet /noreboot"

    - name: Inform user to reboot manually after upgrade
      debug:
        msg: "✅ Windows 11 setup has started. Please allow the system to reboot or reboot manually to continue installation."

