- name: Trigger Windows 11 upgrade via Windows Update
  hosts: all
  gather_facts: no
  tasks:

    - name: Enable telemetry and diagnostic data (helps get Windows 11 offer)
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection
        name: AllowTelemetry
        data: 3
        type: dword

    - name: Allow upgrade to Windows 11 via TargetReleaseVersion
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: TargetReleaseVersion
        data: 1
        type: dword

    - name: Set TargetReleaseVersionInfo to Windows 11
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: TargetReleaseVersionInfo
        data: "Windows 11"
        type: string

    - name: Force Windows Update to scan for updates
      win_shell: |
        UsoClient StartScan
      args:
        executable: powershell.exe

    - name: Start download and install if update available
      win_shell: |
        UsoClient StartDownload; UsoClient StartInstall
      args:
        executable: powershell.exe

    - name: Show notification to user
      win_shell: |
        Add-Type -AssemblyName PresentationFramework
        [System.Windows.MessageBox]::Show('🚀 Windows Update triggered. If this PC is eligible, Windows 11 will begin installing soon. Please check Windows Update settings.')
      args:
        executable: powershell.exe
