---
- name: Install Google Chrome on Windows
  hosts: 192.168.33.55
  gather_facts: yes
  tasks:
    - name: Install Google Chrome via Chocolatey
      win_chocolatey:
        name: googlechrome
        state: present
