- name: Upgrade Windows 10 Pro to Windows 11 Pro (Safe and Non-destructive)
  hosts: all
  gather_facts: no
  vars:
    upgrade_url: "https://go.microsoft.com/fwlink/?linkid=2171764"
    upgrade_path: "C:\\Temp\\Windows11Upgrade.exe"

  tasks:
    - name: Ensure Temp folder exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download Windows 11 Installation Assistant
      win_get_url:
        url: "{{ upgrade_url }}"
        dest: "{{ upgrade_path }}"
        validate_certs: yes

    - name: Launch Windows 11 Installation Assistant
      win_command: "{{ upgrade_path }}"
