---
- name: Install Notepad++ on Windows
  hosts: 192.168.33.72  # Directly specify the host IP
  tasks:
    - name: Install Notepad++ via Chocolatey
      win_chocolatey:
        name: notepadplusplus
        state: present
