- name: Upgrade Windows 10 Pro to Windows 11 Pro using Installation Assistant
  hosts: all
  gather_facts: no
  vars:
    assistant_url: "https://go.microsoft.com/fwlink/?linkid=2171764"
    assistant_path: "C:\\Temp\\Windows11InstallationAssistant.exe"

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Download Windows 11 Installation Assistant
      win_get_url:
        url: "{{ assistant_url }}"
        dest: "{{ assistant_path }}"
        validate_certs: yes

    - name: Run Windows 11 Installation Assistant (interactive upgrade)
      win_shell: |
        Start-Process -FilePath "{{ assistant_path }}" -Verb RunAs
      args:
        executable: powershell.exe

    - name: ✅ Upgrade assistant launched — complete manually
      debug:
        msg: "✅ Windows 11 Installation Assistant has been launched. Please complete the upgrade on the remote system."
